// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MainnetJs from "mainnet-js";

console.log("Hello, World!");

MainnetJs.TestNetWallet.newRandom().then(function (wallet) {
        return MainnetJs.TestNetWallet.watchOnly(wallet.address);
      }).then(function (watchOnlyWallet) {
      console.log(watchOnlyWallet);
    });

export {
  
}
/*  Not a pure module */
